### ISSUE TITLE
"Run file analysis" mode not working.

### ISSUE THREAD

**Issue by RamVedantham** [jmecosta/VSSonarQubeExtension#116]
I am seeing the following exception in output window soon after my project is opened in Visual studio.
<exception>
VSSonarExtensionMetroVs2013:Object reference not set to an instance of an object. :    at VSSonarQubeExtension.Helpers.VsPropertiesHelper.VsFileItem(String filename, Resource associatedProject, Resource fileResource)
   at VSSonarExtensionUi.ViewModel.SonarQubeViewModel.CreateAResourceForFileInEditor(String fullName)
   at VSSonarExtensionUi.ViewModel.SonarQubeViewModel.RefreshDataForResource(String fullName)
   at VSSonarQubeExtension.Helpers.VsEvents.WindowActivated(Window gotFocus, Window lostFocus)
<exception>

I am seeing the following info when I opened the "Issues output window"

NSonarQubeRunner : Check Rule Could Not Be Used SonarQube.CSharp.CodeAnalysis.Rules.CommentRegularExpression : Object reference not set to an instance of an object.
27-05-2015 17:23:24:NSonarQubeRunner : Checks Availalbe:  : 56 :  - csharpsquid:S1066 - csharpsquid:S1117 - csharpsquid:S1313 - csharpsquid:S2225 - csharpsquid:S1244 - csharpsquid:S1854 - csharpsquid:S2328 - csharpsquid:S2228 - csharpsquid:S2070 - csharpsquid:S2123 - csharpsquid:S2326 - csharpsquid:S2325 - csharpsquid:S2234 - csharpsquid:S1940 - csharpsquid:S2758 - csharpsquid:S2757 - csharpsquid:S1121 - csharpsquid:S2306 - csharpsquid:S1301 - csharpsquid:S1227 - csharpsquid:S2737 - csharpsquid:S125 - csharpsquid:S2760 - csharpsquid:S1862 - csharpsquid:S1871 - csharpsquid:S126 - csharpsquid:S2486 - csharpsquid:S1186 - csharpsquid:S108 - csharpsquid:S1116 - csharpsquid:S127 - csharpsquid:S1994 - csharpsquid:S1764 - csharpsquid:S1145 - csharpsquid:S2681 - csharpsquid:S1848 - csharpsquid:S1226 - csharpsquid:S1109 - csharpsquid:S1656 - csharpsquid:S1697 - csharpsquid:S2743 - csharpsquid:S131 - csharpsquid:S105 - csharpsquid:S1125 - csharpsquid:S1481 - csharpsquid:S121 - csharpsquid:S101 - csharpsquid:S1067 - csharpsquid:S104 - csharpsquid:S1541 - csharpsquid:S103 - csharpsquid:S109 - csharpsquid:S100 - csharpsquid:S1479 - csharpsquid:S107
27-05-2015 17:23:24:NSonarQubeRunner : Checks Enabled 0
27-05-2015 17:23:24:StyleCopRunner : Analyse: C:\xxxxxxxx\yyyy.csproj
27-05-2015 17:23:25:StyleCopRunner : Issues Found: 0 

Please let me know why "Run file analysis" mode is not working while "Incremental", "Preview" modes are working absolutely fine.

**Comment by jmecosta** [comment]
You have issues with the association, is not able find the correct
association. Can you share your properties file?

**Comment by RamVedantham** [comment]
# required metadata
sonar.projectKey=xxxx
sonar.projectName=yyyy
sonar.projectVersion=1.0

sources=.
# The value of the property must be the key of the language.
sonar.language=cs
sonar.dotnet.visualstudio.solution.file=xxx.Tests.sln
#sonar.donet.visualstudio.testProjectPattern=*.Unit

sonar.visualstudio.enable=true


# Gallio
sonar.gallio.installDirectory=C:/Gallio
#sonar.NCover.installDirectory=C:/Program Files (x86)/NCover
#sonar.gallio.coverage.tool=NCover
sonar.gallio.mode=reuseReport
# sonar.gallio.mode=skip

 # gendarme
sonar.gendarme.installDirectory=c:/Program Files (x86)/Gendarme
#sonar.gendarme.mode=enabled
   
 # FXCop
sonar.fxcop.installDirectory=C:/Program Files (x86)/Microsoft FxCop 10.0
sonar.fxcop.ignoreGeneratedCode=true
sonar.fxcop.ignoreexitcode=12
#sonar.fxcop.mode=enabled
sonar.fxcop.mode=skip  
   
 #StyleCop  
 sonar.stylecop.installDirectory=C:/Program Files (x86)/StyleCop 4.7
#sonar.stylecop.mode=enabled 
sonar.ndeps.mode=skip 
# Encoding of sources files
sonar.sourceEncoding=UTF-8

**Comment by jmecosta** [comment]
Is this the file that you use to run a full analysis? Or you just create it
to run incremental analysis. What sonar version and dot net plugins are you
currently running on server?

**Comment by RamVedantham** [comment]
Yes this is the file I am using for running Incremental and preview analysis. (They both are running fine.)

Sonarqube 4.0 version.
C# Core [csharp]	2.0
C# StyleCop [csharpstylecop]	2.0
.NET Core [dotnet]	2.0	
.NET FxCop [dotnetfxcop]	
.NET Gallio [dotnetgallio]	2.0	
.NET Gendarme [dotnetgendarme]	2.0	
.NET NDeps [dotnetndeps]	2.0

**Comment by jmecosta** [comment]
Yep not supported. File analysis requires you to use the latest version of
the c# plugin.

**Comment by RamVedantham** [comment]
was it working before (v 3.1.1.0)?

**Comment by jmecosta** [comment]
Nop, file analysis for c# is new in v3

**Comment by jmecosta** [comment]
@RamVedantham please reopen if problems persist
