### ISSUE TITLE
Server connection settings not retained

### ISSUE THREAD

**Issue by debashish2014** [jmecosta/VSSonarQubeExtension#118]
Connection settings added in general setting is lost once the visual studio restarts. Once the connection settings is saved, it should remain there even though we restart the visual studio.

**Comment by jmecosta** [comment]
What version of the extension are you using

**Comment by debashish2014** [comment]
I am using version 3.1.4.3

**Comment by jmecosta** [comment]
Once you upgrade to version 3.1.4.3 those will be wiped, but after the
first try it should work. Did you try restarting after the upgrade? If yes
please tell me your environment. Vs version, windows

**Comment by debashish2014** [comment]
I haven't upgraded to the version. I directly installed version 3.1.4.3 available on website. After installing the plugin, I tried to connect to sonar qube server by providing the server address and it got authenticated and I was able to connect. Once I restarted the visual studio the server address I previously entered was lost. I am using visual studio premium 2013 version 12 update 2.

**Comment by jmecosta** [comment]
Can you upgrade to update 4? Most likely not the issue

**Comment by debashish2014** [comment]
I couldn't find new version at this link https://visualstudiogallery.msdn.microsoft.com/7fc312c3-f1ab-49f8-b286-dbf7fff37305 nor in the extension manager. From where should I install version 4 of the plugin?

**Comment by jmecosta** [comment]
i mean update 4 of vs 2013.
https://www.microsoft.com/en-us/download/details.aspx?id=44921

**Comment by debashish2014** [comment]
Thanks. I will update visual studio and let you know.

**Comment by debashish2014** [comment]
I have installed vs update 4, but the issue still persists. It is loosing the connection settings. I tried to reinstall the plugin as well, but it didn't worked.

**Comment by jmecosta** [comment]
@debashish2014 i will try to create a debug version for you to see whats going on. not sure based on your input

**Comment by jmecosta** [comment]
@debashish2014 can you let me know if you still have issues with 4.0.1.1?
