### ISSUE TITLE
Clicking on issue in issues grid, does to take you to line of code

### ISSUE THREAD

**Issue by debashish2014** [jmecosta/VSSonarQubeExtension#119]
Clicking on issue in issues grid does to take you to line of code in the file where the issue is, in local analysis mode.

**Comment by jmecosta** [comment]
Do you have a sonar properties along with your solution file?

**Comment by debashish2014** [comment]
No, I don't have sonar properties along with the solution file.

**Comment by jmecosta** [comment]
you you need to have one, so that the extension can figure the key type used during analysis. see https://github.com/jmecosta/VSSonarQubeExtension/tree/master/sampleProjects and try one. those are the supported project types at the moment

**Comment by jmecosta** [comment]
@debashish2014 can you check with this: https://github.com/jmecosta/VSSonarQubeExtension/releases/tag/4.0.0-Beta-1 perhapps now its fixed

**Comment by jmecosta** [comment]
Please reopen if its still a issue
