### ISSUE TITLE
Local Anaysis not working

### ISSUE THREAD

**Issue by binamrathapa** [jmecosta/VSSonarQubeExtension#123]
Create JDBC datasource for jdbc:h2:
Testing JDBC connection
Initializing Hibernate
hibernate.generate_statistics: false
hibernate.dialect: org.hibernate.dialect.H2Dialect
hibernate.connection.provider_class: org.sonar.jpa.session.CustomHibernateConnectionProvider
Loaded 3537 properties from l10n bundles
INFO: ------------------------------------------------------------------------
INFO: EXECUTION FAILURE
INFO: ------------------------------------------------------------------------
Total time: 38.220s
ERROR: Error during Sonar runner execution
Final Memory: 32M/249M
INFO: ------------------------------------------------------------------------
org.sonar.runner.impl.RunnerException: Unable to execute Sonar
	at org.sonar.runner.impl.BatchLauncher$1.delegateExecution(BatchLauncher.java:91)
	at org.sonar.runner.impl.BatchLauncher$1.run(BatchLauncher.java:75)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.sonar.runner.impl.BatchLauncher.doExecute(BatchLauncher.java:69)
	at org.sonar.runner.impl.BatchLauncher.execute(BatchLauncher.java:50)
	at org.sonar.runner.api.EmbeddedRunner.doExecute(EmbeddedRunner.java:102)
	at org.sonar.runner.api.Runner.execute(Runner.java:100)
	at org.sonar.runner.Main.executeTask(Main.java:70)
	at org.sonar.runner.Main.execute(Main.java:59)
	at org.sonar.runner.Main.main(Main.java:53)

**Comment by jmecosta** [comment]
hi,
do you have a sonar-project.properties available in same locations as the solution file?

**Comment by binamrathapa** [comment]
Yes, I have put onlye these information in sonar-project.properties.
sonar.sources=./
sonar.language=cs

Then, ran Incremental Analysis. Analysis is successful but it displayed Exception Found message.
![attachment](https://cloud.githubusercontent.com/assets/13516220/9137175/abf095a0-3d3b-11e5-918f-814dde5d68ea.png)
Error message
![error_message](https://cloud.githubusercontent.com/assets/13516220/9137208/ec93a2fa-3d3b-11e5-8997-6748e544610b.png)

**Comment by jmecosta** [comment]
Please share your environment. Fsharp runtime issues

**Comment by jmecosta** [comment]
Can you try to install this package:
https://www.microsoft.com/en-us/download/details.aspx?id=34675

see if the redist packages get into your environment

**Comment by binamrathapa** [comment]
I installed and but not working.

**Comment by jmecosta** [comment]
@binamrathapa i am working on a new version, lets check when its release

**Comment by binamrathapa** [comment]
Sure. Thanks for help

**Comment by jmecosta** [comment]
@binamrathapa can you check with this: https://github.com/jmecosta/VSSonarQubeExtension/releases/tag/4.0.0-Beta-1 perhapps now its fixed

**Comment by binamrathapa** [comment]
I downloaded and installed. I set all setting as previous one. Authentication is ok. After that, I open vs2012, it gave this error
![error_after_4version](https://cloud.githubusercontent.com/assets/13516220/9300374/fd9ef1d4-44e4-11e5-872b-c40d9f27bf63.png)

**Comment by jmecosta** [comment]
What is your sonar version?

**Comment by jmecosta** [comment]
also can you set the following environment variable

VSSONAREXTENSIONDEBUGVERBOSE=true

and enable the extension in debug mode in the general options.

This will create additional log files in your 
C:\Users\<user>\AppData\Roaming\VSSonarExtension

we need to check the communication in those.. and the replies from server

**Comment by binamrathapa** [comment]
server sonar version 4.5

**Comment by binamrathapa** [comment]
Local analysis is working in vs2013. After that, it displayed analysis log. License is not found or expired in message column. Below attached image is correct for local analysis? Actually, what are displayed in local analysis. Please can you describe me.
![local_analysis_issue](https://cloud.githubusercontent.com/assets/13516220/9302064/4decdecc-44f3-11e5-942b-08bb9ca27fe0.png)

**Comment by jmecosta** [comment]
Thats is correct, you need a license to perform local analysis in c# projects. you should be able to run up to 5 analysis. if you require a trial please go to the site mentioned in the message.

Anyway, 2012 version is it ok now?

**Comment by binamrathapa** [comment]
No,
I set VSSONAREXTENSIONDEBUGVERBOSE=true and only two files (debug.log.11.0 and settings.cfg.11.0) in location C:\Users<user>\AppData\Roaming\VSSonarExtension. But the information are encrypted.
I saw on ActivityLog.xml. It writes these error:
<entry>
    <record>273</record>
    <time>2015/08/17 08:08:11.115</time>
    <type>Error</type>
    <source>Editor or Editor Extension</source>
    <description>System.ArgumentNullException: Value cannot be null.&#x000D;&#x000A;Parameter name: Object reference not set to an instance of an object.&#x000D;&#x000A;   at VSSonarQubeExtension.Squiggle.SonarTagger..ctor(ITextBuffer sourceBuffer)&#x000D;&#x000A;   at VSSonarQubeExtension.Squiggle.SonarTagger.SonarTaggerProvider.&lt;&gt;c__DisplayClass12_0`1.&lt;CreateTagger&gt;b__0()&#x000D;&#x000A;   at Microsoft.VisualStudio.Utilities.PropertyCollection.GetOrCreateSingletonProperty[T](Object key, Func`1 creator)&#x000D;&#x000A;   at VSSonarQubeExtension.Squiggle.SonarTagger.SonarTaggerProvider.CreateTagger[T](ITextView textView, ITextBuffer buffer)&#x000D;&#x000A;   at Microsoft.VisualStudio.Text.Tagging.Implementation.TagAggregator`1.GatherTaggers(ITextBuffer textBuffer)</description>
  </entry>
  <entry>
    <record>274</record>
    <time>2015/08/17 08:08:12.875</time>
    <type>Error</type>
    <source>Editor or Editor Extension</source>
    <description>System.NullReferenceException: Object reference not set to an instance of an object.&#x000D;&#x000A;   at VSSonarQubeExtension.Coverage.HighlightCoverageTagger.&lt;GetTags&gt;d__11.MoveNext()&#x000D;&#x000A;   at Microsoft.VisualStudio.Text.Tagging.Implementation.TagAggregator`1.&lt;GetTagsForBuffer&gt;d__16.MoveNext()</description>
  </entry>
  <entry>
    <record>275</record>
    <time>2015/08/17 08:08:16.872</time>
    <type>Error</type>
    <source>Editor or Editor Extension</source>
    <description>System.NullReferenceException: Object reference not set to an instance of an object.&#x000D;&#x000A;   at VSSonarQubeExtension.Coverage.HighlightCoverageTagger.&lt;GetTags&gt;d__11.MoveNext()&#x000D;&#x000A;   at Microsoft.VisualStudio.Text.Tagging.Implementation.TagAggregator`1.&lt;GetTagsForBuffer&gt;d__16.MoveNext()</description>
  </entry>

**Comment by jmecosta** [comment]
The debug log should not be encrypted. Can you check that one

**Comment by binamrathapa** [comment]
Only this text:
Window Activated: Kind: Tool

**Comment by jmecosta** [comment]
Ok, i got the same problem in one of my machines.. I will investigate now here

**Comment by jmecosta** [comment]
@binamrathapa so the issue with vs 2012 is related with changes introduced in the one of the libs that  uses f# 3.1. Those changes are not ported back to f# 3.0 and because vs 2012 uses f# 3.0 it fails.

unfortunately the only way i was able to make it work is to update the binding redirect for vs 2012... like this

in
C:\Program Files (x86)\Microsoft Visual Studio 11.0\Common7\IDE\devenv.exe.config add a new entry like this

			<dependentAssembly>
				<assemblyIdentity name="FSharp.Core" publicKeyToken="b03f5f7f11d50a3a" culture="neutral" />
				<bindingRedirect oldVersion="0.0.0.0-4.3.1.0" newVersion="4.3.1.0" />
			</dependentAssembly>

Now there are 2 options, i stop supporting vs 2012 or people that use it need to apply this workaround. Could you try to verify that it works for you?

**Comment by jmecosta** [comment]
I will still try something at run time see if it helps

**Comment by jmecosta** [comment]
@binamrathapa can you try to download again, https://github.com/jmecosta/VSSonarQubeExtension/releases/download/4.0.0-Beta-1/VSSonarExtensionMetroVs2012.vsix unistall the existent and install again. it should be working now

**Comment by binamrathapa** [comment]
Now, it is also working in vs2012.
Thanks, so much.

**Comment by jmecosta** [comment]
thanks for testing.

**Comment by binamrathapa** [comment]
Hi,
I used trial license for local analysis. When I double click on .cs file of component column of local analysis. It gave error.
![double_click_issue](https://cloud.githubusercontent.com/assets/13516220/9351704/7a3d708e-467b-11e5-8653-a70b93e9e469.png)

Error is:
8/19/2015 4:03:33 AM:SonarRestService:The remote server returned an error: (404) Not Found. :    at SonarRestService.JsonSonarConnector.SonarRestService-IHttpSonarConnector-HttpSonarGetRequest(ISonarConfiguration userConf, String url)
   at SonarRestService.SonarRestService.VSSonarPlugins-ISonarRestService-GetResourcesData(ISonarConfiguration conf, String resource)
   at VSSonarExtensionUi.ViewModel.Helpers.IssueGridViewModel.OnOpenInVsCommand(Object parameter)
8/19/2015 4:03:33 AM:OnInEditor : Object reference not set to an instance of an object. : App_Code/CSCode/pdashOps.cs
8/19/2015 4:03:33 AM:OnInEditor  : Solution = Frame_US33045
8/19/2015 4:03:33 AM:OnInEditor : Project = VSSonarPlugins.Types.Resource
8/19/2015 4:03:33 AM:SonarLocalAnalyser:Object reference not set to an instance of an object. :    at SonarLocalAnalyser.SQKeyTranslator.SonarLocalAnalyser-ISQKeyTranslator-TranslateKey(String key, IVsEnvironmentHelper vshelper, String branchIn)
   at VSSonarExtensionUi.ViewModel.Helpers.IssueGridViewModel.OnOpenInVsCommand(Object parameter)

**Comment by jmecosta** [comment]
Hi, its not related with trial license. Can you open a new issue describing
the problem. Would be great if I could get access to some resource keys in
your server

**Comment by binamrathapa** [comment]
Hi,
I download this trial license(AnalysisPlugin.VSQ). Actually, we don't need the license for cs? only required for vb. Please can you describe me about this license.

**Comment by jmecosta** [comment]
Please ask a message via the support page, same where you ask for trial.

**Comment by binamrathapa** [comment]
ok.
